lab-2
Asutaaa/Is-2022-Web pull request #4
Opened 2022-10-22 16:47 UTC by Asutaaa

2022-10-24 11:56 UTC, BakasaRus requested changes
1. Межстрочный интервал через `line-height`
2. Красная строка через `text-indent`
3. Расстояние между словами/буквами через `word-spacing` / `letter-spacing`
4. Капс через CSS с помощью `text-transform`

2022-10-24 11:56 UTC, BakasaRus commented on css/style.css
> +	font-family: Verdana;
Надо подобрать и подключить шрифт из Google Fonts

2022-10-24 11:56 UTC, BakasaRus commented on css/style.css
> +	background-color: #00185c;
Из чего состоит эта штука?

2022-11-18 14:12 UTC, Asutaaa commented on css/style.css
> +	font-family: Verdana;
Исправила

2022-11-18 14:21 UTC, Asutaaa commented on css/style.css
> +	background-color: #00185c;
Представление цвета в шестнадцатеричной системе счисления. В RGB этот цвет будет  (0. 24. 92).

2022-11-19 18:49 UTC, BakasaRus commented on css/style.css
> +	font-family: Verdana;
А где?) Пока что не вижу новых коммитов

2022-11-19 18:55 UTC, BakasaRus approved these changes

2022-12-04 17:09 UTC, merged